apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typeform-chatbot.fullname" . }}-secrets
  labels:
    {{- include "typeform-chatbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  PINECONE_API_KEY: {{ .Values.secrets.pineconeApiKey | quote }}
